<?php

function HookDisable_rightclickAllAdditionalheaderjs() {
    global $baseurl_short;
    echo '<script src="' . $baseurl_short . 'plugins/disable_rightclick/libs/ProtectImage.js/src/ProtectImage.min.js"></script>';
    
    // Initialization script for ProtectImage.js
    echo '<script>
    window.addEventListener("load", function() {
        ProtectImageJS.protect(document.querySelectorAll("img"));
    });
    
    </script>';
    
    // Commenting out the inclusion of context_menu.js for now
    // echo '<script src="' . $baseurl_short . 'plugins/disable_rightclick/js/context_menu.js"></script>';
}

function HookDisable_rightclickAllPreheaderoutput(){
    global $baseurl, $pagename;

    // Only add the noscript tag if we're not on the login page
    if ($pagename !== 'login') {
        echo '<noscript>
            <meta http-equiv="refresh" content="0;url=' . $baseurl . '/plugins/disable_rightclick/pages/js_disabled.php">
        </noscript>';
    }
}

function HookDisable_rightclickRender_actions_add_collection() {
    // Start output buffering to capture action links generated by ResourceSpace
    ob_start();
}

function HookDisable_rightclickRender_actions_add_collection_end() {
    // Get buffered output
    $actionLinks = ob_get_clean();

    // Ensure we only capture relevant links, and sanitize the output
    if (strpos($actionLinks, 'download.php') !== false || strpos($actionLinks, 'share.php') !== false) {
        global $disable_rightclick_actions;
        $disable_rightclick_actions = htmlspecialchars($actionLinks, ENT_QUOTES, 'UTF-8');
    }
}

function HookDisable_rightclickRender_after_resource_actions() {
    global $disable_rightclick_actions;
    
    if (isset($disable_rightclick_actions)) {
        // Display the context menu
        echo "<div class='custom-context-menu'>{$disable_rightclick_actions}</div>";
        
        // Generate the sub-menu for downloads (this is a simplified version for demonstration)
        $menu = "<div class='custom-context-menu-item download-option'>Download";
        $menu .= "<div class='download-sub-menu'>";
        $menu .= "<a href='#' class='custom-context-menu-item'>Download Original</a>";
        $menu .= "<a href='#' class='custom-context-menu-item'>Download Watermarked</a>";
        $menu .= "</div></div>";

        echo $menu;
    }
}