<?php

function Hookprotect_imageAllAdditionalheaderjs() {
    global $baseurl_short;
    echo '<script src="' . $baseurl_short . 'plugins/protect_image/libs/ProtectImage.js/src/ProtectImage.min.js"></script>';
    // Initialization script for ProtectImage.js;
    echo '<script src="' . $baseurl_short . 'plugins/protect_image/js/ProtectImageInit.js"></script>';
}

function Hookprotect_imageAllHeadblock(){
    global $baseurl, $pagename;

    // Only add the noscript tag if we're not on the login page
    if ($pagename !== 'login') {
        echo '<noscript>
            <meta http-equiv="refresh" content="0;url=' . $baseurl . '/plugins/protect_image/pages/js_disabled.php">
        </noscript>';
    }
}

function Hookprotect_imageRender_actions_add_collection() {
    // Start output buffering to capture action links generated by ResourceSpace
    ob_start();
}

function Hookprotect_imageRender_actions_add_collection_end() {
    // Get buffered output
    $actionLinks = ob_get_clean();

    // Ensure we only capture relevant links, and sanitize the output
    if (strpos($actionLinks, 'download.php') !== false || strpos($actionLinks, 'share.php') !== false) {
        global $protect_image_actions;
        $protect_image_actions = htmlspecialchars($actionLinks, ENT_QUOTES, 'UTF-8');
    }
}

function Hookprotect_imageRender_after_resource_actions() {
    global $protect_image_actions;
    
    if (isset($protect_image_actions)) {
        // Display the context menu
        echo "<div class='custom-context-menu'>{$protect_image_actions}</div>";
        
        // Generate the sub-menu for downloads (this is a simplified version for demonstration)
        $menu = "<div class='custom-context-menu-item download-option'>Download";
        $menu .= "<div class='download-sub-menu'>";
        $menu .= "<a href='#' class='custom-context-menu-item'>Download Original</a>";
        $menu .= "<a href='#' class='custom-context-menu-item'>Download Watermarked</a>";
        $menu .= "</div></div>";

        echo $menu;
    }
}